apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-storage
  namespace: loki
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-static
  volumeName: loki-storage
  resources:
    requests:
      storage: 50Gi
