apiVersion: v1
kind: ConfigMap
metadata:
  name: ntfy-config
  namespace: ntfy
data:
  server.yml: |
    base-url: "https://ntfy.prakash.com.br"
    listen-http: ":80"
    behind-proxy: true

    cache-file: "/var/cache/ntfy/cache.db"
    cache-duration: "12h"

    auth-file: "/var/cache/ntfy/auth.db"
    auth-default-access: "deny-all"

    enable-signup: false
    enable-login: true
    enable-reservations: false
