apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ntfy
  name: ntfy
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ntfy
  template:
    metadata:
      labels:
        app: ntfy
    spec:
      containers:
      - name: ntfy
        image: binwiederhier/ntfy:v2.22.0
        args: ["serve"]
        ports:
        - containerPort: 80
          name: http
        readinessProbe:
          httpGet:
            path: /v1/health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /v1/health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 3
        volumeMounts:
        - name: config
          mountPath: /etc/ntfy
        - name: cache
          mountPath: /var/cache/ntfy
        resources:
          requests:
            memory: "64Mi"
            cpu: "20m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      volumes:
      - name: config
        configMap:
          name: ntfy-config
      - name: cache
        persistentVolumeClaim:
          claimName: ntfy-cache
---
apiVersion: v1
kind: Service
metadata:
  name: ntfy
  namespace: ntfy
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: ntfy
