apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-cache
  namespace: ntfy
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-static
  volumeName: ntfy-cache
  resources:
    requests:
      storage: 5Gi
