apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: umami-secrets
  namespace: umami
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: umami
    kind: ClusterSecretStore
  target:
    name: umami-secrets
    creationPolicy: Owner
  dataFrom:
    - find:
        name:
          regexp: ".*"
