apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ghcr.io/argoproj/argo-helm
    chart: argocd-image-updater
    targetRevision: 1.0.4
    helm:
      valuesObject:
        config:
          registries:
            - name: ghcr
              api_url: https://ghcr.io
              prefix: ghcr.io
              credentials: secret:argocd/ghcr-image-updater#creds
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
