apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
    # Install cert-manager from Helm chart
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.14.3
      helm:
        values: |
          crds:
            enabled: true
    # Custom resources (ClusterIssuer, Certificate, ExternalSecret)
    - repoURL: https://github.com/prem-prakash/homeserver.git
      targetRevision: main
      path: gitops/cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      jsonPointers:
        - /spec/data/0/remoteRef/conversionStrategy
        - /spec/data/0/remoteRef/decodingStrategy
        - /spec/data/0/remoteRef/metadataPolicy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
