apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iddh-members-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/camilohollanda/homeserver.git
    targetRevision: main
    path: gitops/production/iddh-members
  destination:
    server: https://kubernetes.default.svc
    namespace: iddh-members-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
