apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mailpit-secrets
  namespace: mailpit
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: mailpit
    kind: ClusterSecretStore
  target:
    name: mailpit-secrets
    creationPolicy: Owner
  data:
    - secretKey: MAILPIT_BASIC_USER
      remoteRef:
        key: MAILPIT_BASIC_USER
    - secretKey: MAILPIT_BASIC_PASS
      remoteRef:
        key: MAILPIT_BASIC_PASS
