apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: victoria-metrics-storage
  namespace: victoria-metrics
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-static
  volumeName: victoria-metrics-storage
  resources:
    requests:
      storage: 20Gi
