apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: werify-secrets
  namespace: werify-production
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: werify-production
    kind: ClusterSecretStore
  target:
    name: secrets
    creationPolicy: Owner
  dataFrom:
    - find:
        name:
          regexp: ".*"
