apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: werify-uploads
  namespace: werify-production
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Gi
