apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: plane
  annotations:
    argocd.argoproj.io/sync-wave: '-2'
spec:
  conditions:
    - namespaces: [plane]
  provider:
    infisical:
      hostAPI: https://infisical.internal.prakash.com.br
      auth:
        universalAuthCredentials:
          clientId:
            name: infisical-credentials
            namespace: external-secrets
            key: clientId
          clientSecret:
            name: infisical-credentials
            namespace: external-secrets
            key: clientSecret
      secretsScope:
        projectSlug: homeserver-1jj1
        environmentSlug: prod
        secretsPath: /Plane/
