apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pdf-secrets
  namespace: pdf-staging
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: pdf-staging
    kind: ClusterSecretStore
  target:
    name: secrets
    creationPolicy: Owner
  dataFrom:
    - find:
        name:
          regexp: ".*"
