apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: iddh-members-secrets
  namespace: iddh-members-staging
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: iddh-members-staging
    kind: ClusterSecretStore
  target:
    name: secrets
    creationPolicy: Owner
  dataFrom:
    - find:
        name:
          regexp: ".*"
