#!/usr/bin/env bash
# Re-render the pinned upstream chart. Requires Helm 3+ and Python with PyYAML.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
CHART_VERSION=1.8.0
CHART_SHA256=4b65d1178b39705ce2640257e4b584379f2dfbb2be20fb2b8607bddcb953778f
TASK_TMP="$(mktemp -d)"
trap 'rm -rf "$TASK_TMP"' EXIT
curl -fsSL "https://github.com/makeplane/helm-charts/releases/download/plane-ce-${CHART_VERSION}/plane-ce-${CHART_VERSION}.tgz" -o "$TASK_TMP/chart.tgz"
printf '%s  %s\n' "$CHART_SHA256" "$TASK_TMP/chart.tgz" | shasum -a 256 -c - >/dev/null
helm template plane "$TASK_TMP/chart.tgz" --namespace plane --kube-version 1.34.3 \
  --values "$ROOT/gitops/plane/values.yaml" > "$TASK_TMP/rendered.yaml"
python3 - "$TASK_TMP/rendered.yaml" "$ROOT/gitops/plane/upstream.yaml" <<'PY'
import sys
from pathlib import Path
import yaml

docs = list(yaml.safe_load_all(Path(sys.argv[1]).read_text()))
for doc in docs:
    if not doc:
        continue
    if doc['kind'] == 'Secret':
        raise SystemExit('Refusing to render a Secret: all credentials must come from ESO.')
    # Upstream adds Helm's now() to deployments and the migration Job. Strip it
    # so identical versions/values produce identical GitOps desired state.
    metadata = doc.get('spec', {}).get('template', {}).get('metadata', {})
    annotations = metadata.get('annotations', {})
    annotations.pop('timestamp', None)
    if not annotations:
        metadata.pop('annotations', None)
Path(sys.argv[2]).write_text(
    '# Generated by scripts/plane/render.sh from plane-ce 1.8.0. Do not edit.\n'
    + yaml.safe_dump_all([d for d in docs if d], sort_keys=False)
)
PY
echo "Rendered gitops/plane/upstream.yaml"
