apiVersion: v1
kind: PersistentVolume
metadata:
  name: mailpit-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path-static
  local:
    path: /mnt/k8s-persistent/pvs/mailpit-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-apps
