apiVersion: v1
kind: PersistentVolume
metadata:
  name: victoria-metrics-storage
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path-static
  local:
    path: /mnt/k8s-persistent/pvs/victoria-metrics
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3s-apps
