apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: iddh-members-secrets
  namespace: iddh-members-production
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: iddh-members-production
    kind: ClusterSecretStore
  target:
    name: secrets
    creationPolicy: Owner
  dataFrom:
    - find:
        name:
          regexp: ".*"
