{
 "title": "Werify",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Log volume by level — PRODUCTION",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({namespace=\"werify-production\", app=\"werify\"} [$__auto]))"
    }
   ]
  },
  {
   "title": "Log volume by level — STAGING",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({namespace=\"werify-staging\", app=\"werify\"} [$__auto]))"
    }
   ]
  },
  {
   "title": "Werify PRODUCTION",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"werify-production\", app=\"werify\"} | json | line_format `{{ if .message }}{{ .time | default \"-\" }} {{ .severity | default \"-\" }} {{ .message }}{{ else }}{{ __line__ }}{{ end }}`\n"
    }
   ]
  },
  {
   "title": "Werify STAGING",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"werify-staging\", app=\"werify\"} | json | line_format `{{ if .message }}{{ .time | default \"-\" }} {{ .severity | default \"-\" }} {{ .message }}{{ else }}{{ __line__ }}{{ end }}`\n"
    }
   ]
  }
 ]
}