apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: shared
    kind: ClusterSecretStore
  target:
    name: argocd-notifications-secret
    creationPolicy: Merge
  data:
    - secretKey: ntfy-token
      remoteRef:
        key: NTFY_ARGOCD_TOKEN
